### ISSUE TITLE
Initializerの無効化がされていない。

### ISSUE THREAD

**Issue by cryptedy** [tejastice/edupass-update#1]
https://github.com/tejastice/edupass-update/blob/12d33b77fedc6eb5ea1570733836cf125f45bd0c/contracts/EPASSVer2.sol#L29C2-L29C2

実装コントラクトはproxyから参照されることが前提ですが、直接コールすることもできてしまいます。
V2にはselfdestructはないためリスクは低いものの、基本的に実装コントラクトは安全のためにコンストラクタでinitializerを無効化することが推奨されています。
こちらを参照ください。
https://www.certik.com/resources/blog/FnfYrOCsy3MG9s9gixfbJ-upgradeable-proxy-contract-security-best-practices

またOZのwizardでもデフォルトで以下のコードが入ります。

```solidity
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }
```

**Comment by cryptedy** [comment]
ちなみに、コードはいじらずにinitializeを直でコールしてもokです。V1はinitializeを実行しておくことをおすすめします。

**Comment by tejastice** [comment]
イニシャライザーを無効にするコンストラクタを追加しました。
