### ISSUE TITLE
Initializerは不要

### ISSUE THREAD

**Issue by cryptedy** [tejastice/edupass-update#2]
https://github.com/tejastice/edupass-update/blob/12d33b77fedc6eb5ea1570733836cf125f45bd0c/contracts/EPASSVer2.sol#L29C2-L29C2

proxyコントラクトは初期化済みでこれ以上initialize()をコールすることはできないため、V2以降はinitialize()は不要です。
ただしコードの連続性を維持して可読性を確保する目的であれば残しておいても問題ありません
（コントラクトサイズは増えます）

**Comment by tejastice** [comment]
別のissueで解決済みのためcloseします
