### ISSUE TITLE
引数ownerがpublic変数名と名前衝突している

### ISSUE THREAD

**Issue by cryptedy** [tejastice/edupass-update#3]
https://github.com/tejastice/edupass-update/blob/12d33b77fedc6eb5ea1570733836cf125f45bd0c/contracts/EPASSVer2.sol#L161-L167

ownerはOwnerableUpgradeで使われています。
`owner_`や`newOwner`などに変更すべきです。
（このままでもコンパイラが適切に処理すると思いますが）

**Comment by tejastice** [comment]
引数の名前を変更しました。
